site_name: RealtimeTTS Documentation
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          build: true
          default: true  # Added default: true for English
        - locale: fr
          name: Français
          build: true
        - locale: es
          name: Español
          build: true  
        - locale: de  
          name: Deutsch  
          build: true  
        - locale: it  
          name: Italiano
          build: true  
nav:
  - Home: 
    - English: en/index.md
    - Français: fr/index.md
    - Español: es/index.md  
    - Deutsch: de/index.md  
    - Italiano: it/index.md  
  - Installation: 
    - English: en/installation.md
    - Français: fr/installation.md
    - Español: es/installation.md  
    - Deutsch: de/installation.md  
    - Italiano: it/installation.md  
  - Usage: 
    - English: en/usage.md
    - Français: fr/usage.md
    - Español: es/usage.md  
    - Deutsch: de/usage.md  
    - Italiano: it/usage.md  
  - API Reference: 
    - English: en/api.md
    - Français: fr/api.md
    - Español: es/api.md  
    - Deutsch: de/api.md  
    - Italiano: it/api.md 
  - Contributing: 
    - English: en/contributing.md
    - Français: fr/contributing.md
    - Español: es/contributing.md  
    - Deutsch: de/contributing.md 
    - Italiano: it/contributing.md  
  - FAQ: 
    - English: en/faq.md
    - Français: fr/faq.md
    - Español: es/faq.md  
    - Deutsch: de/faq.md  
    - Italiano: it/faq.md  
